# Generated by Django 2.1.5 on 2019-01-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='level',
            field=models.CharField(default='Beginner', max_length=20),
            preserve_default=False,
        ),
    ]
