# Generated by Django 2.1.5 on 2019-01-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0005_auto_20190117_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='target',
            field=models.CharField(default='Hamstrings', max_length=25),
            preserve_default=False,
        ),
    ]
