# Generated by Django 2.1.5 on 2019-01-15 23:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=500, upload_to='')),
                ('description', models.CharField(max_length=500)),
                ('target', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SavedRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('practice', models.CharField(choices=[('strength', 'Strength'), ('mobility', 'Mobility')], max_length=15)),
                ('targets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pose', models.ManyToManyField(related_name='routine_poses', to='align.Pose')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='savedroutine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routines', to='align.User'),
        ),
    ]
