# Generated by Django 2.1.5 on 2019-01-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0003_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='sequence',
            new_name='poses',
        ),
        migrations.AddField(
            model_name='sequence',
            name='name',
            field=models.CharField(default='idk', max_length=50),
            preserve_default=False,
        ),
    ]
