# Generated by Django 2.1.5 on 2019-01-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0007_auto_20190119_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='height',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pose',
            name='width',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
